language: php

services:
  - docker

matrix:
  include:
    - php: 7.1
      env:
        - DEPS=lowest
    - php: 7.1
      env:
        - DEPS=latest
    - php: 7.2
      env:
        - DEPS=lowest
    - php: 7.2
      env:
        - DEPS=latest
        - PUBLISH_COVERAGE=true
        - PUBLISH_DOCS=true

before_install:
  - pecl install grpc

install:
  - if [[ $DEPS == 'latest' ]]; then travis_retry composer update --no-interaction --prefer-source ; fi
  - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --no-interaction --prefer-source --prefer-lowest ; fi
  - if [[ $PUBLISH_COVERAGE == 'true' ]]; then travis_retry composer require --dev php-coveralls/php-coveralls --no-interaction ; fi

script:
  - composer validate
  - composer lint:syntax
  - composer lint:style
  - composer lint:final
  - if [[ $PUBLISH_COVERAGE != 'true' ]]; then composer test ; fi
  - if [[ $PUBLISH_COVERAGE == 'true' ]]; then composer coverage ; fi
  - composer fixture:up && sleep 30 && composer test:integration
  - composer test:mutations
  - if [[ $PUBLISH_DOCS == 'true' ]]; then composer docs ; fi

after_success:
  - if [[ $PUBLISH_COVERAGE == 'true' ]]; then travis_retry php vendor/bin/php-coveralls ; fi
